fix: Changes in Dockerfile

diff --git a/Dockerfile.development b/Dockerfile.development
--- a/Dockerfile.development
+++ b/Dockerfile.development
@@ -25,10 +25,26 @@ RUN \
   else echo "Lockfile not found." && exit 1; \
   fi
 
+# ========================================
+# Builder Stage
+# ========================================
+FROM base AS builder
+WORKDIR /app
+COPY . .
+COPY --from=deps /app/node_modules ./node_modules
+
+
 # Next.js collects completely anonymous telemetry data about general usage.
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
 ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # ========================================
 # Runner Stage
@@ -44,10 +60,11 @@ ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN adduser --system --uid 1001 nextjs -G node
 
-# Remove this line if you do not have this folder
-
 COPY --chown=nextjs:node . .
 COPY --from=deps --chown=nextjs:node /app/node_modules ./node_modules
+# Remove this line if you do not have this folder
+COPY --from=builder --chown=nextjs:node /app/public /app/public
+
 
 # Set the correct permission for prerender cache
 RUN mkdir .next
@@ -55,6 +72,8 @@ RUN chown nextjs:node .next
 
 RUN mkdir /app/public/media
 RUN chown nextjs:node /app/public/media
+
+COPY --from=builder --chown=nextjs:node /app/.next/static ./.next/static
 
 USER nextjs
 
