fix: Change Dockerfile
- Change Dockerfile
- Change Dockerfile.development

diff --git a/Dockerfile.development b/Dockerfile.development
--- a/Dockerfile.development
+++ b/Dockerfile.development
@@ -6,7 +6,11 @@
 FROM node:22-alpine AS base
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat python3 make g++ git curl bash
-RUN npm install --global corepack@latest
+
+ARG NODE_ENV=development
+ENV NODE_ENV=$NODE_ENV
+
+RUN npm install --global corepack@10.32.0
 RUN corepack enable pnpm
 
 # ========================================
@@ -29,28 +33,34 @@ RUN \
 # ========================================
 # Builder Stage
 # ========================================
-# FROM base AS builder
-# WORKDIR /app
-# COPY . .
-# COPY --from=deps /app/node_modules ./node_modules
+FROM base AS builder
+RUN corepack enable pnpm
+WORKDIR /app
+
+ARG NODE_ENV=development
+ENV NODE_ENV=$NODE_ENV
+
+COPY . .
+COPY --from=deps /app/node_modules ./node_modules
 
 
 # Next.js collects completely anonymous telemetry data about general usage.
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
-# ENV NEXT_TELEMETRY_DISABLED 1
+ENV NEXT_TELEMETRY_DISABLED 1
 
-# RUN \
-#   if [ -f yarn.lock ]; then yarn run build; \
-#   elif [ -f package-lock.json ]; then npm run build; \
-#   elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
-#   else echo "Lockfile not found." && exit 1; \
-#   fi
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # ========================================
 # Runner Stage
 # ========================================
 FROM base AS runner
+RUN corepack enable pnpm
 WORKDIR /app
 
 ARG NODE_ENV=development
@@ -63,15 +73,13 @@ RUN adduser --system --uid 1001 nextjs -G node
 
 COPY --chown=nextjs:node . .
 COPY --from=deps --chown=nextjs:node /app/node_modules ./node_modules
-# Remove this line if you do not have this folder
-# COPY --from=builder --chown=nextjs:node /app/public /app/public
-
 
 # Set the correct permission for prerender cache
 RUN mkdir .next
 RUN chown nextjs:node .next
 
-# COPY --from=builder --chown=nextjs:node /app/.next/static ./.next/static
+COPY --from=builder --chown=nextjs:node /app/.next ./.next
+COPY --from=builder --chown=nextjs:node /app/public ./public
 
 USER nextjs
 
